# Generated by Django 5.1.5 on 2025-02-12 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrableProductDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_of_administration', models.CharField(max_length=255)),
                ('dosage_form', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('strength', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('identifier', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceStudyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=255)),
                ('effectiveness', models.DecimalField(decimal_places=3, max_digits=6)),
                ('effect_time', models.CharField(max_length=127)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('symptom_disease', models.CharField(blank=True, max_length=255)),
                ('field_of_study', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('authors', models.CharField(blank=True, max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('CID', models.CharField(blank=True, default='CID-NÃO-ESPECIFICADO', max_length=50, null=True)),
                ('not_indicated', models.BooleanField(default=False, verbose_name='Não Indicado para Uso')),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('element_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('study_group_idade', models.CharField(choices=[('0-10', '0 a 10 anos'), ('11-20', '11 a 20 anos'), ('21-30', '21 a 30 anos'), ('31-60', '31 a 60 anos'), ('61-70', '61 a 70 anos'), ('71-80', '71 a 80 anos'), ('81+', '81 anos ou mais'), ('gravidez', 'Gravidez'), ('lactante', 'Lactante')], max_length=20, verbose_name='Faixa Etária')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('evidencia_clinica', models.TextField()),
                ('principio_ativo', models.CharField(max_length=200)),
                ('fabricante', models.CharField(max_length=200)),
                ('avaliacao', models.DecimalField(decimal_places=2, max_digits=3)),
                ('eficacia_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('eficacia_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prazo_efeito_min', models.CharField(max_length=50)),
                ('prazo_efeito_max', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('evidencia_clinica', models.TextField()),
                ('principio_ativo', models.CharField(max_length=200)),
                ('fabricante', models.CharField(max_length=200)),
                ('avaliacao', models.DecimalField(decimal_places=2, max_digits=3)),
                ('eficacia_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('eficacia_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prazo_efeito_min', models.CharField(max_length=50)),
                ('prazo_efeito_max', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturedItemDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('form', models.CharField(max_length=255)),
                ('ingredients', models.ManyToManyField(related_name='manufactured_items', to='core.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicinalProductDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('administrable_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicinal_products', to='core.administrableproductdefinition')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicinal_products', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalUseDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contraindications', models.TextField(blank=True, null=True)),
                ('indications', models.TextField(blank=True, null=True)),
                ('interactions', models.TextField(blank=True, null=True)),
                ('adverse_effects', models.TextField(blank=True, null=True)),
                ('medicinal_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_uses', to='core.medicinalproductdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='Binary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=100)),
                ('data', models.BinaryField()),
                ('medicinal_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binaries', to='core.medicinalproductdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('section_text', models.TextField()),
                ('medicinal_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='core.medicinalproductdefinition')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PackagedProductDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('manufactured_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaged_products', to='core.manufactureditemdefinition')),
            ],
        ),
        migrations.AddField(
            model_name='administrableproductdefinition',
            name='packaged_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrable_products', to='core.packagedproductdefinition'),
        ),
        migrations.CreateModel(
            name='RegulatedAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_number', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('date_issued', models.DateField()),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='core.organization')),
                ('medicinal_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='core.medicinalproductdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='SubstanceDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('molecular_formula', models.CharField(blank=True, max_length=255, null=True)),
                ('molecular_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substances', to='core.organization')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='substance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='core.substancedefinition'),
        ),
    ]
