# Generated by Django 5.1.5 on 2025-01-31 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrableProductDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_of_administration', models.CharField(max_length=255)),
                ('dosage_form', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('strength', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('identifier', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturedItemDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('form', models.CharField(max_length=255)),
                ('ingredients', models.ManyToManyField(related_name='manufactured_items', to='core.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicinalProductDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('administrable_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicinal_products', to='core.administrableproductdefinition')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicinal_products', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalUseDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contraindications', models.TextField(blank=True, null=True)),
                ('indications', models.TextField(blank=True, null=True)),
                ('interactions', models.TextField(blank=True, null=True)),
                ('adverse_effects', models.TextField(blank=True, null=True)),
                ('medicinal_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_uses', to='core.medicinalproductdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='PackagedProductDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('manufactured_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaged_products', to='core.manufactureditemdefinition')),
            ],
        ),
        migrations.AddField(
            model_name='administrableproductdefinition',
            name='packaged_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrable_products', to='core.packagedproductdefinition'),
        ),
        migrations.CreateModel(
            name='RegulatedAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_number', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('date_issued', models.DateField()),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='core.organization')),
                ('medicinal_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='core.medicinalproductdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='SubstanceDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('molecular_formula', models.CharField(blank=True, max_length=255, null=True)),
                ('molecular_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substances', to='core.organization')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='substance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='core.substancedefinition'),
        ),
    ]
