# Generated by Django 5.1.5 on 2025-02-23 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contraindicacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "imagem",
                    models.ImageField(
                        blank=True, null=True, upload_to="contraindicacoes/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contraindicação",
                "verbose_name_plural": "Contraindicações",
            },
        ),
        migrations.CreateModel(
            name="ReacaoAdversa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "imagem",
                    models.ImageField(
                        blank=True, null=True, upload_to="reacoes_adversas/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Reação Adversa",
                "verbose_name_plural": "Reações Adversas",
            },
        ),
        migrations.CreateModel(
            name="DetalhesTratamentoResumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("categoria", models.CharField(blank=True, max_length=100, null=True)),
                ("evidencia_clinica", models.TextField(blank=True, null=True)),
                ("principio_ativo", models.CharField(max_length=200)),
                ("fabricante", models.CharField(max_length=200)),
                (
                    "avaliacao",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "eficacia_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "eficacia_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "prazo_efeito_min",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "prazo_efeito_max",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="tratamentos/"),
                ),
                (
                    "grau_evidencia",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "funciona_para_todos",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("adesao", models.CharField(blank=True, max_length=200, null=True)),
                ("quando_tomar", models.TextField()),
                ("realizar_tratamento_quando", models.TextField(blank=True, null=True)),
                (
                    "custo_medicamento",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("links_externos", models.TextField(blank=True, null=True)),
                ("alertas", models.TextField(blank=True, null=True)),
                (
                    "grupo",
                    models.CharField(
                        choices=[
                            ("criancas", "Crianças menores de 12 anos"),
                            ("adolescentes", "Adolescentes 12 a 17 anos"),
                            ("idosos", "Idosos +65 anos"),
                            ("adultos", "Adultos"),
                            ("lactantes", "Lactantes"),
                            ("gravidez", "Gravidez"),
                        ],
                        default="adultos",
                        max_length=20,
                    ),
                ),
                (
                    "indicado_criancas",
                    models.CharField(
                        choices=[("SIM", "Sim"), ("NÃO", "Não")],
                        default="NÃO",
                        max_length=100,
                    ),
                ),
                ("motivo_criancas", models.TextField(blank=True, null=True)),
                (
                    "indicado_adolescentes",
                    models.CharField(
                        choices=[("SIM", "Sim"), ("NÃO", "Não")],
                        default="NÃO",
                        max_length=100,
                    ),
                ),
                ("motivo_adolescentes", models.TextField(blank=True, null=True)),
                (
                    "indicado_idosos",
                    models.CharField(
                        choices=[("SIM", "Sim"), ("NÃO", "Não")],
                        default="NÃO",
                        max_length=100,
                    ),
                ),
                ("motivo_idosos", models.TextField(blank=True, null=True)),
                (
                    "indicado_adultos",
                    models.CharField(
                        choices=[("SIM", "Sim"), ("NÃO", "Não")],
                        default="SIM",
                        max_length=100,
                    ),
                ),
                ("motivo_adultos", models.TextField(blank=True, null=True)),
                (
                    "uso_lactantes",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C")],
                        default="C",
                        max_length=100,
                    ),
                ),
                ("motivo_lactantes", models.TextField(blank=True, null=True)),
                (
                    "uso_gravidez",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("X", "X"),
                        ],
                        default="D",
                        max_length=100,
                    ),
                ),
                ("motivo_gravidez", models.TextField(blank=True, null=True)),
                (
                    "contraindicacoes",
                    models.ManyToManyField(blank=True, to="core.contraindicacao"),
                ),
                (
                    "reacoes_adversas",
                    models.ManyToManyField(blank=True, to="core.reacaoadversa"),
                ),
            ],
            options={
                "verbose_name": "Detalhes Tratamentos - Resumo",
                "verbose_name_plural": "Detalhes Tratamentos - Resumo",
            },
        ),
        migrations.CreateModel(
            name="EvidenciasClinicas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                (
                    "Condicao_saude",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("grau_evidencia", models.CharField(max_length=100)),
                (
                    "estudo_publicado",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("link_estudo", models.URLField(blank=True, null=True)),
                ("data_publicacao", models.DateField(blank=True, null=True)),
                ("autores", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "imagem_estudo",
                    models.ImageField(blank=True, null=True, upload_to="evidencias/"),
                ),
                ("eficacia_min", models.DecimalField(decimal_places=2, max_digits=5)),
                ("eficacia_max", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "pdf_estudo",
                    models.FileField(blank=True, null=True, upload_to="pdf_estudos/"),
                ),
                ("link_pdf_estudo", models.URLField(blank=True, null=True)),
                ("referencia_bibliografica", models.TextField(blank=True, null=True)),
                (
                    "tratamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidencias",
                        to="core.detalhestratamentoresumo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidência Clínica",
                "verbose_name_plural": "Evidências Clínicas",
            },
        ),
    ]
