# Generated by Django 5.1.6 on 2025-02-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamentos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='tratamentos/'),
        ),
    ]
