# Generated by Django 5.1.5 on 2025-02-24 00:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="evidenciasclinicas",
            old_name="Condicao_saude",
            new_name="condicao_saude",
        ),
    ]
