# Generated by Django 5.1.5 on 2025-01-31 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=100)),
                ('data', models.BinaryField()),
                ('medicinal_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binaries', to='core.medicinalproductdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('section_text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='core.organization')),
                ('medicinal_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='core.medicinalproductdefinition')),
            ],
        ),
    ]
