# Generated by Django 5.1.5 on 2025-02-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_binary_composition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceStudyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=255)),
                ('effectiveness', models.DecimalField(decimal_places=3, max_digits=6)),
                ('effect_time', models.CharField(max_length=127)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('symptom_disease', models.CharField(blank=True, max_length=255)),
                ('field_of_study', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('authors', models.CharField(blank=True, max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('CID', models.CharField(blank=True, default='CID-NÃO-ESPECIFICADO', max_length=50, null=True)),
                ('not_indicated', models.BooleanField(default=False, verbose_name='Não Indicado para Uso')),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('element_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('study_group_idade', models.CharField(choices=[('0-10', '0 a 10 anos'), ('11-20', '11 a 20 anos'), ('21-30', '21 a 30 anos'), ('31-60', '31 a 60 anos'), ('61-70', '61 a 70 anos'), ('71-80', '71 a 80 anos'), ('81+', '81 anos ou mais'), ('gravidez', 'Gravidez'), ('lactante', 'Lactante')], default='0-10', max_length=20, verbose_name='Faixa Etária')),
            ],
        ),
    ]
