# Generated by Django 5.1.5 on 2025-02-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tratamentos_imagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tratamento',
        ),
    ]
