# Generated by Django 5.1.5 on 2025-02-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_tratamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamentos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='medicamentos/'),
        ),
    ]
