# Generated by Django 5.1.5 on 2025-02-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_detalhestratamentoresumo_delete_tratamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalhestratamentoresumo',
            name='eficacia',
        ),
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='eficacia_max',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='eficacia_min',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
