# Generated by Django 5.1.5 on 2025-02-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_detalhestratamentoresumo_eficacia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='grupo',
            field=models.CharField(choices=[('criancas', 'Crianças menores de 12 anos'), ('adolescentes', 'Adolescentes 12 a 17 anos'), ('idosos', 'Idosos +65 anos'), ('adultos', 'Adultos'), ('lactantes', 'Lactantes'), ('gravidez', 'Gravidez')], default='adultos', max_length=20),
        ),
    ]
