# Generated by Django 5.1.5 on 2025-02-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_detalhestratamentoresumo_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='imagem_hipersensibilidade',
            field=models.ImageField(blank=True, null=True, upload_to='contraindicacoes/'),
        ),
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='imagem_hipertensao',
            field=models.ImageField(blank=True, null=True, upload_to='contraindicacoes/'),
        ),
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='imagem_insuficiencia_hepatica',
            field=models.ImageField(blank=True, null=True, upload_to='contraindicacoes/'),
        ),
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='imagem_insuficiencia_renal',
            field=models.ImageField(blank=True, null=True, upload_to='contraindicacoes/'),
        ),
    ]
