# Generated by Django 5.1.5 on 2025-02-16 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_detalhestratamentoresumo_imagem_hipersensibilidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciasClinicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('grau_evidencia', models.CharField(max_length=100)),
                ('estudo_publicado', models.CharField(blank=True, max_length=255, null=True)),
                ('link_estudo', models.URLField(blank=True, null=True)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('autores', models.CharField(blank=True, max_length=255, null=True)),
                ('imagem_estudo', models.ImageField(blank=True, null=True, upload_to='evidencias/')),
                ('pdf_estudo', models.FileField(blank=True, null=True, upload_to='pdf_estudos/')),
                ('link_pdf_estudo', models.URLField(blank=True, null=True)),
                ('tratamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='core.detalhestratamentoresumo')),
            ],
            options={
                'verbose_name': 'Evidência Clínica',
                'verbose_name_plural': 'Evidências Clínicas',
            },
        ),
    ]
