# Generated by Django 5.1.5 on 2025-02-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_evidenciasclinicas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contraindicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='contraindicacoes/')),
            ],
        ),
    ]
