# Generated by Django 5.1.5 on 2025-02-17 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contraindicacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contraindicacao',
            new_name='Contraindicacoes',
        ),
    ]
