# Generated by Django 5.1.5 on 2025-02-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_contraindicacao_contraindicacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReacaoAdversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('comum', 'Comum'), ('incomum', 'Incomum'), ('rara', 'Rara'), ('muito rara', 'Muito Rara')], max_length=50)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='reacoes_adversas/')),
            ],
        ),
    ]
