# Generated by Django 5.1.5 on 2025-02-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_reacaoadversa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contraindicacoes',
        ),
        migrations.DeleteModel(
            name='ReacaoAdversa',
        ),
        migrations.AddField(
            model_name='evidenciasclinicas',
            name='referencia_bibliografica',
            field=models.TextField(blank=True, null=True),
        ),
    ]
