# Generated by Django 5.1.5 on 2025-02-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_evidenciasclinicas_eficacia_max_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contraindicacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "imagem",
                    models.ImageField(
                        blank=True, null=True, upload_to="contraindicacoes/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contraindicação",
                "verbose_name_plural": "Contraindicações",
            },
        ),
        migrations.CreateModel(
            name="ReacaoAdversa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "imagem",
                    models.ImageField(
                        blank=True, null=True, upload_to="reacoes_adversas/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Reação Adversa",
                "verbose_name_plural": "Reações Adversas",
            },
        ),
        migrations.AlterModelOptions(
            name="detalhestratamentoresumo",
            options={},
        ),
        migrations.RemoveField(
            model_name="detalhestratamentoresumo",
            name="contraindicado_hipersensibilidade",
        ),
        migrations.RemoveField(
            model_name="detalhestratamentoresumo",
            name="contraindicado_hipertensao",
        ),
        migrations.RemoveField(
            model_name="detalhestratamentoresumo",
            name="contraindicado_insuficiencia_hepatica",
        ),
        migrations.RemoveField(
            model_name="detalhestratamentoresumo",
            name="contraindicado_insuficiencia_renal",
        ),
        migrations.RemoveField(
            model_name="detalhestratamentoresumo",
            name="imagem_hipersensibilidade",
        ),
        migrations.RemoveField(
            model_name="detalhestratamentoresumo",
            name="imagem_hipertensao",
        ),
        migrations.RemoveField(
            model_name="detalhestratamentoresumo",
            name="imagem_insuficiencia_hepatica",
        ),
        migrations.RemoveField(
            model_name="detalhestratamentoresumo",
            name="imagem_insuficiencia_renal",
        ),
        migrations.RemoveField(
            model_name="detalhestratamentoresumo",
            name="imagem_reacao",
        ),
        migrations.RemoveField(
            model_name="detalhestratamentoresumo",
            name="motivo_hipersensibilidade",
        ),
        migrations.RemoveField(
            model_name="detalhestratamentoresumo",
            name="motivo_hipertensao",
        ),
        migrations.RemoveField(
            model_name="detalhestratamentoresumo",
            name="motivo_insuficiencia_hepatica",
        ),
        migrations.RemoveField(
            model_name="detalhestratamentoresumo",
            name="motivo_insuficiencia_renal",
        ),
        migrations.RemoveField(
            model_name="detalhestratamentoresumo",
            name="opiniao_medica",
        ),
        migrations.RemoveField(
            model_name="detalhestratamentoresumo",
            name="reacoes_adversas",
        ),
    ]
