# Generated by Django 5.1.5 on 2025-02-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_contraindicacao_reacaoadversa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalhestratamentoresumo",
            name="contraindicacoes",
            field=models.ManyToManyField(blank=True, to="core.contraindicacao"),
        ),
        migrations.AddField(
            model_name="detalhestratamentoresumo",
            name="reacoes_adversas",
            field=models.ManyToManyField(blank=True, to="core.reacaoadversa"),
        ),
    ]
