# Generated by Django 5.1.5 on 2025-02-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_detalhestratamentoresumo_contraindicacoes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalhestratamentoresumo',
            options={'verbose_name': 'Detalhes Tratamentos - Resumo', 'verbose_name_plural': 'Detalhes Tratamentos - Resumo'},
        ),
        migrations.RenameField(
            model_name='detalhestratamentoresumo',
            old_name='uso_gravidez',
            new_name='indicado_gravidez',
        ),
        migrations.RenameField(
            model_name='detalhestratamentoresumo',
            old_name='uso_lactantes',
            new_name='indicado_lactantes',
        ),
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='avaliacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='evidencia_clinica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidenciasclinicas',
            name='condicao_saude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detalhestratamentoresumo',
            name='adesao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detalhestratamentoresumo',
            name='eficacia_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalhestratamentoresumo',
            name='eficacia_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='detalhestratamentoresumo',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
