# Generated by Django 5.1.5 on 2025-03-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_detalhestratamentoresumo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='risco',
            field=models.FloatField(default=0.0, help_text='Risco percentual de efeito colateral (0 a 100%)'),
        ),
    ]
