# Generated by Django 5.1.5 on 2025-03-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_evidenciasclinicas_reacoes_adversas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidenciasclinicas',
            name='reacoes_adversas',
        ),
        migrations.AddField(
            model_name='evidenciasclinicas',
            name='risco_reacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
