# Generated by Django 5.1.5 on 2025-03-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_evidenciasclinicas_reacoes_adversas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reacaoadversa',
            name='risco_reacao',
            field=models.FloatField(default=0.0, help_text='Risco percentual de efeito colateral (0 a 100%)'),
        ),
    ]
