# Generated by Django 5.1.5 on 2025-04-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_grau_evidencia_detalhestratamentoresumo_confiabilidade_pesquisa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reacaoadversa',
            name='risco_reacao',
        ),
        migrations.AddField(
            model_name='reacaoadversa',
            name='reacao_max',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor mánimo de risco percentual de efeito colateral (0 a 100%)', max_digits=5, verbose_name='Reação Máxima (%)'),
        ),
        migrations.AddField(
            model_name='reacaoadversa',
            name='reacao_min',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor mínimo de risco percentual de efeito colateral (0 a 100%)', max_digits=5, verbose_name='Reação Mínima (%)'),
        ),
        migrations.AlterField(
            model_name='detalhestratamentoresumo',
            name='prazo_efeito_max',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalhestratamentoresumo',
            name='prazo_efeito_min',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reacaoadversa',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
