# Generated by Django 5.1.5 on 2025-05-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_evidenciasclinicas_estudo_publicado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalhestratamentoresumo',
            name='adesao',
        ),
    ]
