# Generated by Django 5.1.5 on 2025-05-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_detalhestratamentoresumo_confiabilidade_pesquisa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalhestratamentoresumo',
            old_name='quando_tomar',
            new_name='quando_usar',
        ),
    ]
