# Generated by Django 5.1.5 on 2025-05-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_quando_tomar_detalhestratamentoresumo_quando_usar'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciasclinicas',
            name='numero_participantes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
