# Generated by Django 5.1.5 on 2025-05-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_evidenciasclinicas_numero_participantes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalhestratamentoresumo',
            old_name='realizar_tratamento_quando',
            new_name='tipo_tratamento',
        ),
    ]
