# Generated by Django 5.1.5 on 2025-05-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_rename_realizar_tratamento_quando_detalhestratamentoresumo_tipo_tratamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidenciasclinicas',
            old_name='grau_evidencia',
            new_name='rigor_da_pesquisa',
        ),
        migrations.AlterField(
            model_name='detalhestratamentoresumo',
            name='tipo_tratamento',
            field=models.CharField(choices=[('comprimidos', 'Comprimidos'), ('gotas', 'Gotas'), ('agulhas', 'Agulhas'), ('injetavel', 'Injeção')], default='comprimidos', max_length=20),
        ),
    ]
