# Generated by Django 5.1.5 on 2025-05-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_rename_grau_evidencia_evidenciasclinicas_rigor_da_pesquisa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='alerta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='genericos_similares',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='interacao_medicamentosa',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='opiniao_especialista',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='prescricao_eletronica',
            field=models.URLField(blank=True, null=True),
        ),
    ]
