# Generated by Django 5.1.5 on 2025-05-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_detalhestratamentoresumo_alerta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='imagem_detalhes',
            field=models.ImageField(blank=True, null=True, upload_to='tratamentos/detalhes/'),
        ),
    ]
