# Generated by Django 5.1.5 on 2025-05-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_detalhestratamentoresumo_imagem_detalhes'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='links_profissionais',
            field=models.URLField(blank=True, null=True),
        ),
    ]
