# Generated by Django 5.1.5 on 2025-05-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_tratamento_alter_avaliacao_tratamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='rating',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='estrelas',
            field=models.PositiveIntegerField(choices=[(1, '1 estrela'), (2, '2 estrelas'), (3, '3 estrelas'), (4, '4 estrelas'), (5, '5 estrelas')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tratamento',
            name='descricao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
