# Generated by Django 5.1.5 on 2025-05-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_avaliacao_rating_avaliacao_estrelas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
