# Generated by Django 5.1.5 on 2025-05-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_detalhestratamentoresumo_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhestratamentoresumo',
            name='avaliacao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
