# Generated by Django 5.1.5 on 2025-05-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_detalhestratamentoresumo_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='reacaoadversa',
            name='grau_comunalidade',
            field=models.CharField(choices=[('COMUM', 'COMUM'), ('INCOMUM', 'INCOMUM'), ('RARA', 'RARA'), ('MUITO_RARA', 'MUITO RARA')], default='COMUM', max_length=20, verbose_name='Grau de Comunalidade'),
        ),
    ]
