# Generated by Django 5.1.5 on 2025-05-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_reacaoadversa_grau_comunalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tipo de Tratamento',
                'verbose_name_plural': 'Tipos de Tratamento',
            },
        ),
    ]
