# Generated by Django 5.1.5 on 2025-05-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_tipotratamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalhestratamentoresumo',
            name='tipo_tratamento',
        ),
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='tipo_tratamento',
            field=models.ManyToManyField(blank=True, to='core.tipotratamento'),
        ),
    ]
