# Generated by Django 5.1.5 on 2025-05-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_detalhestratamentoresumo_tipo_tratamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciasclinicas',
            name='rigor_da_pesquisa',
            field=models.IntegerField(default=0),
        ),
    ]
