# Generated by Django 5.1.5 on 2025-05-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_evidenciasclinicas_rigor_da_pesquisa'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='prazo_efeito_unidade',
            field=models.CharField(choices=[('minuto', 'Minuto'), ('hora', 'Hora'), ('dia', 'Dia'), ('sessao', 'Sessão'), ('segundo', 'Segundo')], default='minuto', max_length=10),
        ),
    ]
