# Generated by Django 5.1.5 on 2025-05-23 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_detalhestratamentoreacaoadversateste_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reacaoadversa',
            name='grau_comunalidade',
        ),
        migrations.RemoveField(
            model_name='reacaoadversa',
            name='reacao_max',
        ),
        migrations.RemoveField(
            model_name='reacaoadversa',
            name='reacao_min',
        ),
    ]
