# Generated by Django 5.1.5 on 2025-06-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_detalhestratamentoreacaoadversateste_grau_comunalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhestratamentoreacaoadversateste',
            name='grau_comunalidade',
            field=models.CharField(choices=[('RARA', 'RARA'), ('MUITO_RARA', 'MUITO RARA')], default='COMUM', max_length=20),
        ),
    ]
