# Generated by Django 5.1.5 on 2025-07-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_detalhestratamentoresumo_prazo_efeito_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
