# Generated by Django 5.1.5 on 2025-07-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_detalhestratamentoresumo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhestratamentoresumo',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
