# Generated by Django 5.1.5 on 2025-07-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_detalhestratamentoresumo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhestratamentoresumo',
            name='indicado_gravidez',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NÃO', 'Não')], default='SIM', max_length=100),
        ),
        migrations.AlterField(
            model_name='detalhestratamentoresumo',
            name='indicado_lactantes',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NÃO', 'Não')], default='SIM', max_length=100),
        ),
    ]
