# Generated by Django 5.1.5 on 2025-08-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_detalhestratamentoresumo_indicado_gravidez_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicaoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Condição de Saúde')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Condição de Saúde',
                'verbose_name_plural': 'Condições de Saúde',
            },
        ),
    ]
