# Generated by Django 5.1.5 on 2025-08-11 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_condicaosaude'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciasclinicas',
            name='condicao_saude_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='core.condicaosaude'),
        ),
    ]
