# Generated by Django 5.1.5 on 2025-08-11 13:10
from django.db import migrations

def forward(apps, schema_editor):
    CondicaoSaude = apps.get_model('core', 'CondicaoSaude')
    EvidenciasClinicas = apps.get_model('core', 'EvidenciasClinicas')

    for ev in EvidenciasClinicas.objects.all():
        nome = (ev.condicao_saude or "").strip()
        if not nome:
            continue
        # cria ou reutiliza registro na tabela nova
        cs, _ = CondicaoSaude.objects.get_or_create(nome=nome)
        ev.condicao_saude_fk = cs
        ev.save(update_fields=['condicao_saude_fk'])

def backward(apps, schema_editor):
    EvidenciasClinicas = apps.get_model('core', 'EvidenciasClinicas')
    for ev in EvidenciasClinicas.objects.select_related('condicao_saude_fk'):
        if ev.condicao_saude_fk:
            ev.condicao_saude = ev.condicao_saude_fk.nome
            ev.save(update_fields=['condicao_saude'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_evidenciasclinicas_condicao_saude_fk'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
