# core/migrations/0064_remove_evidenciasclinicas_condicao_saude_fk_and_more.py
# Generated by Django 5.1.5 on 2025-08-21 13:44

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_fix_condicao_saude_columns"),
    ]

    operations = [
        # 1) Garante a coluna NO BANCO em DetalhesTratamentoResumo (idempotente)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE core_detalhestratamentoresumo
                    ADD COLUMN IF NOT EXISTS condicao_saude_id bigint;
                    """,
                    reverse_sql="""
                    -- Não removemos no reverse para não quebrar ambientes já rodados
                    """
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="detalhestratamentoresumo",
                    name="condicao_saude",
                    field=models.ForeignKey(
                        to="core.condicaosaude",
                        on_delete=django.db.models.deletion.SET_NULL,
                        null=True,
                        blank=True,
                        related_name="detalhes_tratamento",
                    ),
                ),
            ],
        ),

        # 2) Garante a coluna NO BANCO em EvidenciasClinicas com o NOME certo (idempotente)
        migrations.RunSQL(
            sql="""
DO $$
BEGIN
  -- Se já existir condicao_saude_id, não faz nada
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name='core_evidenciasclinicas' AND column_name='condicao_saude_id'
  ) THEN
    NULL;

  -- Senão, se existir a antiga 'condicao_saude' sem _id, renomeia para o nome padrão de FK
  ELSIF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name='core_evidenciasclinicas' AND column_name='condicao_saude'
  ) THEN
    ALTER TABLE core_evidenciasclinicas
    RENAME COLUMN condicao_saude TO condicao_saude_id;

  -- Senão, cria a coluna já com o nome correto
  ELSE
    ALTER TABLE core_evidenciasclinicas
    ADD COLUMN condicao_saude_id bigint NULL;
  END IF;
END $$;
""",
            reverse_sql="""
-- Não desfaz no reverse pra não quebrar outros ambientes
""",
        ),

        # 3) Agora sim, aplica o estado Django: ALTER para FK (usará condicao_saude_id)
        migrations.AlterField(
            model_name="evidenciasclinicas",
            name="condicao_saude",
            field=models.ForeignKey(
                to="core.condicaosaude",
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True,
                related_name="evidencias",
            ),
        ),
    ]
