# Generated by Django 5.1.5 on 2025-08-21 13:44

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_fix_condicao_saude_columns'),
    ]

    operations = [
        # Não remover o campo "condicao_saude_id", apenas garantir que ele está no banco de dados
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='condicao_saude',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='detalhes_tratamento', to='core.condicaosaude'
            ),
        ),
        migrations.AlterField(
            model_name='evidenciasclinicas',
            name='condicao_saude',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='evidencias', to='core.condicaosaude'
            ),
        ),
    ]
