# Generated by Django 5.1.5 on 2025-08-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_remove_evidenciasclinicas_condicao_saude_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidenciasclinicas',
            name='condicao_saude_fk',
        ),
        migrations.AlterField(
            model_name='condicaosaude',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Relacionada à Condição de Saúde'),
        ),
    ]
