# Generated by Django 5.1.5 on 2025-08-22 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_remove_evidenciasclinicas_condicao_saude_fk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TratamentoCondicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('condicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tratamentos_relacionados', to='core.condicaosaude')),
                ('tratamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condicoes_relacionadas', to='core.detalhestratamentoresumo')),
            ],
            options={
                'unique_together': {('tratamento', 'condicao')},
            },
        ),
    ]
