# Generated by Django 5.1.5 on 2025-08-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_tratamentocondicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEficacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_eficacia', models.CharField(max_length=255, verbose_name='Tipo de Eficácia')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Tipo de Eficácia')),
            ],
        ),
        migrations.AlterModelOptions(
            name='tratamentocondicao',
            options={'verbose_name': 'Tratamento Condição', 'verbose_name_plural': 'Tratamentos Condições'},
        ),
        migrations.AlterUniqueTogether(
            name='tratamentocondicao',
            unique_together=set(),
        ),
    ]
