# Generated by Django 5.1.5 on 2025-08-22 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_tipoeficacia_alter_tratamentocondicao_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EficaciaPorEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_eficacia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evidenciasclinicas')),
                ('tipo_eficacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoeficacia')),
            ],
            options={
                'unique_together': {('evidencia', 'tipo_eficacia')},
            },
        ),
        migrations.AddField(
            model_name='evidenciasclinicas',
            name='tipos_eficacia',
            field=models.ManyToManyField(related_name='evidencias_eficacia', through='core.EficaciaPorEvidencia', to='core.tipoeficacia'),
        ),
    ]
