# Generated by Django 5.1.5 on 2025-08-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_eficaciaporevidencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eficaciaporevidencia',
            name='eficacia_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='eficaciaporevidencia',
            name='eficacia_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
