# Generated by Django 5.1.5 on 2025-08-23 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_eficaciaporevidencia_eficacia_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='condicao_saude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalhes_tratamento', to='core.condicaosaude'),
        ),
        migrations.AlterField(
            model_name='evidenciasclinicas',
            name='condicao_saude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='core.condicaosaude'),
        ),
    ]
