# Generated by Django 5.1.5 on 2025-08-26 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_detalhestratamentoresumo_condicao_saude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamentocondicao',
            name='condicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamentos_relacionados', to='core.condicaosaude'),
        ),
    ]
