# Generated by Django 5.1.5 on 2025-08-26 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_tratamentocondicao_condicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhestratamentoresumo',
            name='condicao_saude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalhes_tratamento', to='core.condicaosaude'),
        ),
        migrations.AlterField(
            model_name='evidenciasclinicas',
            name='condicao_saude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='core.condicaosaude'),
        ),
    ]
