# Generated by Django 5.1.5 on 2025-08-27 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_detalhestratamentoresumo_condicao_saude_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eficaciaporevidencia',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eficaciaporevidencia',
            name='participantes_com_beneficio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eficaciaporevidencia',
            name='participantes_iniciaram_tratamento',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detalhestratamentoresumo',
            name='condicao_saude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalhes_tratamento', to='core.condicaosaude'),
        ),
        migrations.AlterField(
            model_name='eficaciaporevidencia',
            name='evidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eficacia_por_evidencias', to='core.evidenciasclinicas'),
        ),
        migrations.RemoveField(
            model_name='eficaciaporevidencia',
            name='eficacia_max',
        ),
        migrations.RemoveField(
            model_name='eficaciaporevidencia',
            name='eficacia_min',
        ),
        migrations.RemoveField(
            model_name='eficaciaporevidencia',
            name='percentual_eficacia',
        ),
    ]
