# Generated by Django 5.1.5 on 2025-08-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_alter_eficaciaporevidencia_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicaosaude',
            name='condition',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Condition'),
        ),
        migrations.AddField(
            model_name='condicaosaude',
            name='condition_description',
            field=models.TextField(blank=True, null=True, verbose_name='Condition.description'),
        ),
    ]
