# Generated by Django 5.1.5 on 2025-08-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_condicaosaude_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contraindicacao',
            name='contraindication_description',
            field=models.TextField(blank=True, null=True, verbose_name='ClinicalUseDefinition.contraindication-description'),
        ),
        migrations.AddField(
            model_name='contraindicacao',
            name='contraindication_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ClinicalUseDefinition.contraindication-name'),
        ),
    ]
