# Generated by Django 5.1.5 on 2025-08-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_contraindicacao_contraindication_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reacaoadversa',
            name='undesirable_effect_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Efeito Indesejado (ClinicalUseDefinition)'),
        ),
        migrations.AddField(
            model_name='reacaoadversa',
            name='undesirable_effect_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Efeito Indesejado (ClinicalUseDefinition)'),
        ),
    ]
