# Generated by Django 5.1.5 on 2025-08-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_reacaoadversa_undesirable_effect_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipotratamento',
            name='careplan_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CarePlan.type'),
        ),
        migrations.AlterField(
            model_name='reacaoadversa',
            name='undesirable_effect_description',
            field=models.TextField(blank=True, null=True, verbose_name='ClinicalUseDefinition.undesirableEffect-description'),
        ),
        migrations.AlterField(
            model_name='reacaoadversa',
            name='undesirable_effect_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ClinicalUseDefinition.undesirableEffect-name'),
        ),
    ]
