# Generated by Django 5.1.5 on 2025-08-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_tipotratamento_careplan_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciasclinicas',
            name='evidence_description',
            field=models.TextField(blank=True, null=True, verbose_name='Evidence.description'),
        ),
    ]
