# Generated by Django 5.1.5 on 2025-08-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_evidenciasclinicas_evidence_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciasclinicas',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código'),
        ),
    ]
