# Generated by Django 5.1.5 on 2025-08-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_evidenciasclinicas_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciasclinicas',
            name='referencia_bibliografica',
            field=models.TextField(blank=True, null=True, verbose_name='Título do artigo'),
        ),
    ]
