# Generated by Django 5.1.5 on 2025-08-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_alter_evidenciasclinicas_referencia_bibliografica'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciasclinicas',
            name='evidence_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Evidence.title'),
        ),
    ]
