# Generated by Django 5.1.5 on 2025-08-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_evidenciasclinicas_evidence_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciasclinicas',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='evidenciasclinicas',
            name='pais',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='País'),
        ),
    ]
