# Generated by Django 5.1.5 on 2025-09-03 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_evidenciasclinicas_fonte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='tipo_eficacia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoeficacia'),
        ),
    ]
