# Generated by Django 5.1.5 on 2025-09-03 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_detalhestratamentoresumo_tipo_eficacia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhestratamentoresumo',
            name='tipo_eficacia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eficaciaporevidencia'),
        ),
    ]
