# Generated by Django 5.1.5 on 2025-09-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_alter_detalhestratamentoresumo_tipo_eficacia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalhestratamentoresumo',
            name='tipo_eficacia',
        ),
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='tipos_eficacia',
            field=models.ManyToManyField(blank=True, to='core.eficaciaporevidencia'),
        ),
    ]
