# Generated by Django 5.1.5 on 2025-09-03 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_remove_detalhestratamentoresumo_tipo_eficacia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eficaciaporevidencia',
            name='tipo_eficacia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eficacia_por_tipo', to='core.tipoeficacia'),
        ),
    ]
