# Generated by Django 5.1.5 on 2025-09-05 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_alter_eficaciaporevidencia_tipo_eficacia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eficaciaporevidencia',
            name='tipo_eficacia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoeficacia'),
        ),
        migrations.CreateModel(
            name='Eficacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eficacia_por_tipo', to='core.tipoeficacia')),
            ],
        ),
    ]
