# Generated by Django 5.1.5 on 2025-09-05 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_alter_eficaciaporevidencia_tipo_eficacia_eficacia'),
    ]

    operations = [
        migrations.CreateModel(
            name='EficaciaPorTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_eficacia', models.CharField(max_length=255)),
                ('percentual_eficacia_calculado', models.FloatField()),
                ('participantes_iniciaram_tratamento', models.IntegerField()),
                ('participantes_com_beneficio', models.IntegerField()),
                ('tratamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eficacia_por_tipo', to='core.detalhestratamentoresumo')),
            ],
        ),
    ]
