# Generated by Django 5.1.5 on 2025-09-05 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_evidenciasclinicas_participantes_com_beneficio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidenciasclinicas',
            name='participantes_com_beneficio',
        ),
        migrations.RemoveField(
            model_name='evidenciasclinicas',
            name='participantes_iniciaram_tratamento',
        ),
        migrations.DeleteModel(
            name='Eficacia',
        ),
    ]
