# Generated by Django 5.1.5 on 2025-09-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_remove_evidenciasclinicas_participantes_com_beneficio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciasclinicas',
            name='participantes_com_beneficio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evidenciasclinicas',
            name='participantes_iniciaram_tratamento',
            field=models.IntegerField(default=0),
        ),
    ]
