# Generated by Django 5.1.5 on 2025-09-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_evidenciasclinicas_participantes_com_beneficio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciasclinicas',
            name='tipo_eficacia',
            field=models.CharField(choices=[('cura', 'Cura'), ('eliminacao_sintomas', 'Eliminação dos sintomas'), ('reducao_sintomas', 'Redução dos sintomas'), ('prevencao', 'Prevenção')], default='cura', max_length=20),
        ),
    ]
