# Generated by Django 5.1.5 on 2025-09-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_evidenciasclinicas_tipo_eficacia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoeficacia',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipoeficacia',
            name='tipo_eficacia',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='EficaciaPorTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_eficacia', models.CharField(max_length=255)),
                ('percentual_eficacia_calculado', models.FloatField()),
                ('participantes_iniciaram_tratamento', models.IntegerField()),
                ('participantes_com_beneficio', models.IntegerField()),
                ('tipos_eficacia', models.ManyToManyField(blank=True, related_name='eficacias_tipo', to='core.tipoeficacia')),
            ],
        ),
    ]
