# Generated by Django 5.1.5 on 2025-09-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_alter_tipoeficacia_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoeficacia',
            name='eficacia_por_tipo',
            field=models.ManyToManyField(blank=True, related_name='tipos_de_eficacia', to='core.eficaciaportipo'),
        ),
    ]
