# Generated by Django 5.1.5 on 2025-09-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_tipoeficacia_eficacia_por_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciasclinicas',
            name='percentual',
            field=models.IntegerField(default=0),
        ),
    ]
