# Generated by Django 5.1.5 on 2025-09-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_evidenciasclinicas_percentual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciasclinicas',
            name='percentual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
