# Generated by Django 5.1.5 on 2025-09-07 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_alter_evidenciasclinicas_percentual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidenciasclinicas',
            name='tipo_eficacia',
        ),
        migrations.RemoveField(
            model_name='evidenciasclinicas',
            name='tipos_eficacia',
        ),
    ]
