# Generated by Django 5.1.5 on 2025-10-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_remove_evidenciasclinicas_tipo_eficacia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamentos',
            name='eficacia_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tratamentos',
            name='eficacia_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
