# Generated by Django 5.1.5 on 2025-09-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_remove_evidenciasclinicas_tipo_eficacia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tratamentos',
            options={},
        ),
        migrations.RemoveField(
            model_name='tratamentos',
            name='avaliacao',
        ),
        migrations.RemoveField(
            model_name='tratamentos',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='tratamentos',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='tratamentos',
            name='eficacia_max',
        ),
        migrations.RemoveField(
            model_name='tratamentos',
            name='eficacia_min',
        ),
        migrations.RemoveField(
            model_name='tratamentos',
            name='evidencia_clinica',
        ),
        migrations.RemoveField(
            model_name='tratamentos',
            name='fabricante',
        ),
        migrations.RemoveField(
            model_name='tratamentos',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='tratamentos',
            name='prazo_efeito_max',
        ),
        migrations.RemoveField(
            model_name='tratamentos',
            name='prazo_efeito_min',
        ),
        migrations.RemoveField(
            model_name='tratamentos',
            name='principio_ativo',
        ),
        migrations.AddField(
            model_name='tratamentos',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tratamentos',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
