# Generated by Django 5.1.5 on 2025-10-09 20:39

from django.db import migrations, models
from decimal import Decimal



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_alter_tratamentos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tratamentos',
            options={'verbose_name': 'Tratamento Resumo', 'verbose_name_plural': 'Tratamentos - Resumo'},
        ),
        migrations.RemoveField(
            model_name='tratamentos',
            name='slug',
        ),
        migrations.AddField(
            model_name='tipoeficacia',
            name='peso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tratamentos',
            name='avaliacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tratamentos',
            name='categoria',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tratamentos',
            name='descricao',
            field=models.TextField(default='outros'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tratamentos',
            name='eficacia_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tratamentos',
            name='eficacia_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tratamentos',
            name='evidencia_clinica',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tratamentos',
            name='fabricante',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tratamentos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='medicamentos/'),
        ),
        migrations.AddField(
            model_name='tratamentos',
            name='prazo_efeito_max',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tratamentos',
            name='prazo_efeito_min',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tratamentos',
            name='principio_ativo',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tratamentos',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
