# Generated by Django 5.1.5 on 2025-10-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_alter_tratamentos_eficacia_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciasclinicas',
            name='eficacia_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='evidenciasclinicas',
            name='eficacia_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
