# Generated by Django 5.1.5 on 2025-10-20 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_alter_evidenciasclinicas_eficacia_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='tratamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='core.detalhestratamentoresumo'),
        ),
    ]
