# Generated by Django 5.1.5 on 2025-10-21 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_alter_avaliacao_estrelas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
    ]
