# Generated by Django 5.1.5 on 2025-10-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_alter_avaliacao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoeficacia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='icones_eficacia/'),
        ),
    ]
