# Generated by Django 5.1.5 on 2025-11-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_tipoeficacia_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='usuario_nome',
            field=models.CharField(default='Usuário Anônimo', max_length=255),
        ),
    ]
