# Generated by Django 5.1.5 on 2025-11-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_avaliacao_usuario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='usuario_nome',
            field=models.CharField(max_length=100),
        ),
    ]
