# Generated by Django 5.1.5 on 2025-12-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_alter_avaliacao_usuario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciasclinicas',
            name='country',
            field=models.CharField(blank=True, choices=[('Brasil', 'Brasil'), ('Argentina', 'Argentina'), ('Colômbia', 'Colômbia'), ('México', 'México'), ('Chile', 'Chile'), ('Estados Unidos', 'Estados Unidos'), ('França', 'França'), ('Alemanha', 'Alemanha'), ('Reino Unido', 'Reino Unido'), ('Itália', 'Itália'), ('Espanha', 'Espanha'), ('China', 'China'), ('Japão', 'Japão'), ('Índia', 'Índia'), ('Coreia do Sul', 'Coreia do Sul'), ('Austrália', 'Austrália'), ('Nova Zelândia', 'Nova Zelândia'), ('África do Sul', 'África do Sul'), ('Egito', 'Egito'), ('Nigéria', 'Nigéria'), ('Zimbábue', 'Zimbábue'), ('Vários continentes', 'Vários continentes')], max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='evidenciasclinicas',
            name='pais',
            field=models.CharField(blank=True, choices=[('Brasil', 'Brasil'), ('Argentina', 'Argentina'), ('Colômbia', 'Colômbia'), ('México', 'México'), ('Chile', 'Chile'), ('Estados Unidos', 'Estados Unidos'), ('França', 'França'), ('Alemanha', 'Alemanha'), ('Reino Unido', 'Reino Unido'), ('Itália', 'Itália'), ('Espanha', 'Espanha'), ('China', 'China'), ('Japão', 'Japão'), ('Índia', 'Índia'), ('Coreia do Sul', 'Coreia do Sul'), ('Austrália', 'Austrália'), ('Nova Zelândia', 'Nova Zelândia'), ('África do Sul', 'África do Sul'), ('Egito', 'Egito'), ('Nigéria', 'Nigéria'), ('Zimbábue', 'Zimbábue'), ('Vários continentes', 'Vários continentes')], max_length=100, null=True, verbose_name='País'),
        ),
    ]
