from django.db import migrations

# Dicionário de tradução dos países
COUNTRY_TRANSLATION = {
  'Afghanistan': 'Afeganistão',
    'Albania': 'Albânia',
    'Algeria': 'Argélia',
    'Andorra': 'Andorra',
    'Angola': 'Angola',
    'Antigua and Barbuda': 'Antígua e Barbuda',
    'Argentina': 'Argentina',
    'Armenia': 'Armênia',
    'Australia': 'Austrália',
    'Austria': 'Áustria',
    'Azerbaijan': 'Azerbaijão',
    'Bahamas': 'Bahamas',
    'Bahrain': 'Bahrein',
    'Bangladesh': 'Bangladesh',
    'Barbados': 'Barbados',
    'Belarus': 'Bielorrússia',
    'Belgium': 'Bélgica',
    'Belize': 'Belize',
    'Benin': 'Benin',
    'Bhutan': 'Butão',
    'Bolivia': 'Bolívia',
    'Bosnia and Herzegovina': 'Bósnia e Herzegovina',
    'Botswana': 'Botswana',
    'Brazil': 'Brasil',
    'Brunei': 'Brunei',
    'Bulgaria': 'Bulgária',
    'Burkina Faso': 'Burkina Faso',
    'Burundi': 'Burundi',
    'Cabo Verde': 'Cabo Verde',
    'Cambodia': 'Camboja',
    'Cameroon': 'Camarões',
    'Canada': 'Canadá',
    'Central African Republic': 'República Centro-Africana',
    'Chad': 'Chade',
    'Chile': 'Chile',
    'China': 'China',
    'Colombia': 'Colômbia',
    'Comoros': 'Comores',
    'Congo (Congo-Brazzaville)': 'Congo (Congo-Brazzaville)',
    'Congo (Congo-Kinshasa)': 'Congo (Congo-Kinshasa)',
    'Costa Rica': 'Costa Rica',
    'Croatia': 'Croácia',
    'Cuba': 'Cuba',
    'Cyprus': 'Chipre',
    'Czech Republic': 'República Tcheca',
    'Denmark': 'Dinamarca',
    'Djibouti': 'Djibouti',
    'Dominica': 'Dominica',
    'Dominican Republic': 'República Dominicana',
    'Ecuador': 'Equador',
    'Egypt': 'Egito',
    'El Salvador': 'El Salvador',
    'Equatorial Guinea': 'Guiné Equatorial',
    'Eritrea': 'Eritreia',
    'Estonia': 'Estônia',
    'Eswatini': 'Eswatini',
    'Ethiopia': 'Etiópia',
    'Fiji': 'Fiji',
    'Finland': 'Finlândia',
    'France': 'França',
    'Gabon': 'Gabão',
    'Gambia': 'Gâmbia',
    'Georgia': 'Geórgia',
    'Germany': 'Alemanha',
    'Ghana': 'Gana',
    'Greece': 'Grécia',
    'Grenada': 'Granada',
    'Guatemala': 'Guatemala',
    'Guinea': 'Guiné',
    'Guinea-Bissau': 'Guiné-Bissau',
    'Guyana': 'Guiana',
    'Haiti': 'Haiti',
    'Honduras': 'Honduras',
    'Hungary': 'Hungria',
    'Iceland': 'Islândia',
    'India': 'Índia',
    'Indonesia': 'Indonésia',
    'Iran': 'Irã',
    'Iraq': 'Iraque',
    'Ireland': 'Irlanda',
    'Israel': 'Israel',
    'Italy': 'Itália',
    'Jamaica': 'Jamaica',
    'Japan': 'Japão',
    'Jordan': 'Jordânia',
    'Kazakhstan': 'Cazaquistão',
    'Kenya': 'Quênia',
    'Kiribati': 'Quiribati',
    'Korea, North': 'Coreia do Norte',
    'Korea, South': 'Coreia do Sul',
    'Kuwait': 'Kuwait',
    'Kyrgyzstan': 'Quirguistão',
    'Laos': 'Laos',
    'Latvia': 'Letônia',
    'Lebanon': 'Líbano',
    'Lesotho': 'Lesoto',
    'Liberia': 'Libéria',
    'Libya': 'Líbia',
    'Liechtenstein': 'Liechtenstein',
    'Lithuania': 'Lituânia',
    'Luxembourg': 'Luxemburgo',
    'Madagascar': 'Madagascar',
    'Malawi': 'Malawi',
    'Malaysia': 'Malásia',
    'Maldives': 'Maldivas',
    'Mali': 'Mali',
    'Malta': 'Malta',
    'Marshall Islands': 'Ilhas Marshall',
    'Mauritania': 'Mauritânia',
    'Mauritius': 'Maurícias',
    'Mexico': 'México',
    'Micronesia': 'Micronésia',
    'Moldova': 'Moldávia',
    'Monaco': 'Mônaco',
    'Mongolia': 'Mongólia',
    'Montenegro': 'Montenegro',
    'Morocco': 'Marrocos',
    'Mozambique': 'Moçambique',
    'Myanmar': 'Mianmar',
    'Namibia': 'Namíbia',
    'Nauru': 'Nauru',
    'Nepal': 'Nepal',
    'Netherlands': 'Países Baixos',
    'New Zealand': 'Nova Zelândia',
    'Nicaragua': 'Nicarágua',
    'Niger': 'Níger',
    'Nigeria': 'Nigéria',
    'North Macedonia': 'Macédônia do Norte',
    'Norway': 'Noruega',
    'Oman': 'Omã',
    'Pakistan': 'Paquistão',
    'Palau': 'Palau',
    'Panama': 'Panamá',
    'Papua New Guinea': 'Papua Nova Guiné',
    'Paraguay': 'Paraguai',
    'Peru': 'Peru',
    'Philippines': 'Filipinas',
    'Poland': 'Polônia',
    'Portugal': 'Portugal',
    'Qatar': 'Catar',
    'Romania': 'Romênia',
    'Russia': 'Rússia',
    'Rwanda': 'Ruanda',
    'Saint Kitts and Nevis': 'São Cristóvão e Nevis',
    'Saint Lucia': 'Santa Lúcia',
    'Saint Vincent and Grenadines': 'São Vicente e Granadinas',
    'Samoa': 'Samoa',
    'San Marino': 'São Marino',
    'Sao Tome and Principe': 'São Tomé e Príncipe',
    'Saudi Arabia': 'Arábia Saudita',
    'Senegal': 'Senegal',
    'Serbia': 'Sérvia',
    'Seychelles': 'Seychelles',
    'Sierra Leone': 'Serra Leoa',
    'Singapore': 'Singapura',
    'Slovakia': 'Eslováquia',
    'Slovenia': 'Eslovênia',
    'Solomon Islands': 'Ilhas Salomão',
    'Somalia': 'Somália',
    'South Africa': 'África do Sul',
    'South Sudan': 'Sudão do Sul',
    'Spain': 'Espanha',
    'Sri Lanka': 'Sri Lanka',
    'Sudan': 'Sudão',
    'Suriname': 'Suriname',
    'Sweden': 'Suécia',
    'Switzerland': 'Suíça',
    'Syria': 'Síria',
    'Taiwan': 'Taiwan',
    'Tajikistan': 'Tajiquistão',
    'Tanzania': 'Tanzânia',
    'Thailand': 'Tailândia',
    'Timor-Leste': 'Timor-Leste',
    'Togo': 'Togo',
    'Tonga': 'Tonga',
    'Trinidad and Tobago': 'Trinidad e Tobago',
    'Tunisia': 'Tunísia',
    'Turkey': 'Turquia',
    'Turkmenistan': 'Turcomenistão',
    'Tuvalu': 'Tuvalu',
    'Uganda': 'Uganda',
    'Ukraine': 'Ucrânia',
    'United Arab Emirates': 'Emirados Árabes Unidos',
    'United Kingdom': 'Reino Unido',
    'United States': 'Estados Unidos',
    'Uruguay': 'Uruguai',
    'Uzbekistan': 'Uzbequistão',
    'Vanuatu': 'Vanuatu',
    'Vatican City': 'Vaticano',
    'Venezuela': 'Venezuela',
    'Vietnam': 'Vietnã',
    'Yemen': 'Iémen',
    'Zambia': 'Zâmbia',
    'Zimbabwe': 'Zimbábue',
    'Multiple countries in the Americas': 'Vários países da América',
    'Multiple countries in Europe': 'Vários países da Europa',
    'Multiple countries in Asia': 'Vários países da Ásia',
    'Multiple countries in Africa': 'Vários países da África',
    'Multiple countries from more than one continent': 'Vários países de mais de um continente',
}

def update_country_names(apps, schema_editor):
    # Acessando o modelo
    EvidenciasClinicas = apps.get_model('core', 'EvidenciasClinicas')

    # Atualizando os registros existentes
    for old_country, new_country in COUNTRY_TRANSLATION.items():
        # Atualiza os países nos campos 'pais' e 'country'
        EvidenciasClinicas.objects.filter(country=old_country).update(country=new_country)
        EvidenciasClinicas.objects.filter(pais=old_country).update(pais=new_country)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_alter_evidenciasclinicas_country_and_more'),  # Substitua com a migração anterior
    ]

    operations = [
        migrations.RunPython(update_country_names),
    ]
