# Generated by Django 5.1.5 on 2025-12-10 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_update_country_names'),
        ('core', '0111_alter_evidenciasclinicas_country_and_more'),
    ]

    operations = [
    ]
