# Generated by Django 5.1.5 on 2025-12-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_pais_alter_evidenciasclinicas_pais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhestratamentoresumo',
            name='tipos_eficacia',
            field=models.ManyToManyField(related_name='detalhes_tratamento_resumo', to='core.eficaciaporevidencia'),
        ),
    ]
