# Generated by Django 5.1.5 on 2025-12-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_alter_detalhestratamentoresumo_tipos_eficacia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhestratamentoresumo',
            name='tipos_eficacia',
            field=models.ManyToManyField(blank=True, to='core.eficaciaporevidencia'),
        ),
    ]
