# Generated by Django 5.1.5 on 2026-01-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_alter_detalhestratamentoresumo_tipos_eficacia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhestratamentoresumo',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='detalhestratamentoresumo',
            name='fabricante',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='detalhestratamentoresumo',
            name='nome',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='detalhestratamentoresumo',
            name='prazo_efeito_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalhestratamentoresumo',
            name='prazo_efeito_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalhestratamentoresumo',
            name='principio_ativo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='detalhestratamentoresumo',
            name='quando_usar',
            field=models.TextField(blank=True),
        ),
    ]
