# Generated by Django 5.1.5 on 2026-01-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_alter_detalhestratamentoresumo_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhestratamentoresumo',
            name='principio_ativo',
            field=models.CharField(blank=True, max_length=20000),
        ),
    ]
