# Generated by Django 5.1.5 on 2026-02-02 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_alter_detalhestratamentoresumo_principio_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='condicoes_saude',
            field=models.ManyToManyField(blank=True, related_name='detalhes_tratamentos', to='core.condicaosaude'),
        ),
        migrations.CreateModel(
            name='DetalheTratamentoCondicaoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_relacionada', models.TextField(blank=True, null=True)),
                ('condicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.condicaosaude')),
                ('tratamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.detalhestratamentoresumo')),
            ],
            options={
                'unique_together': {('tratamento', 'condicao')},
            },
        ),
    ]
