# Generated by Django 5.1.5 on 2026-02-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_copy_condicao_to_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalhestratamentoresumo',
            name='condicao_saude',
        ),
    ]
