# Generated by Django 5.1.5 on 2026-02-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_remove_detalhestratamentoresumo_condicao_saude'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='link_para_compra_de_tratamento',
            field=models.URLField(blank=True, null=True),
        ),
    ]
