# Generated by Django 5.1.5 on 2026-02-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_detalhestratamentoresumo_link_para_compra_de_tratamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='especificacao_de_custo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
