# Generated by Django 5.1.5 on 2026-02-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_detalhestratamentoresumo_especificacao_de_custo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalhestratamentoresumo',
            old_name='especificacao_de_custo',
            new_name='especificacao_do_custo',
        ),
    ]
