# Generated by Django 5.1.5 on 2026-02-26 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_rename_especificacao_de_custo_detalhestratamentoresumo_especificacao_do_custo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaDetalheTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicada', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('titulo_custom', models.CharField(blank=True, max_length=255)),
                ('descricao_custom', models.TextField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=120)),
                ('cta_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas_tratamento', to='core.condicaosaude')),
                ('tratamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas_publicas', to='core.detalhestratamentoresumo')),
            ],
            options={
                'unique_together': {('condicao', 'tratamento')},
            },
        ),
    ]
