# Generated by Django 5.1.5 on 2026-02-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_paginadetalhetratamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicaosaude',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
