# Generated by Django 5.1.5 on 2026-02-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_condicaosaude_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicaosaude',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
