# Generated by Django 5.1.5 on 2026-03-04 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_alter_condicaosaude_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paginadetalhetratamento',
            options={'verbose_name': 'URL Detalhe', 'verbose_name_plural': 'URLs Detalhes'},
        ),
        migrations.CreateModel(
            name='PaginaListaTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicada', models.BooleanField(default=True)),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('template_name', models.CharField(blank=True, default='core/lista_tratamentos.html', max_length=200)),
                ('condicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paginas_listas', to='core.condicaosaude')),
                ('tipo_eficacia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paginas_listas', to='core.tipoeficacia')),
            ],
            options={
                'verbose_name': 'URLs Listas',
                'verbose_name_plural': 'URLs Listas',
                'unique_together': {('condicao', 'tipo_eficacia')},
            },
        ),
    ]
