# Generated by Django 5.1.5 on 2026-03-05 12:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_alter_paginadetalhetratamento_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paginalistatratamento',
            old_name='condicao',
            new_name='condicao_saude',
        ),
        migrations.AlterUniqueTogether(
            name='paginalistatratamento',
            unique_together={('condicao_saude', 'tipo_eficacia')},
        ),
        migrations.AddField(
            model_name='paginalistatratamento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paginalistatratamento',
            name='template',
            field=models.CharField(default='core/lista_tratamentos.html', help_text='Template django que renderiza a lista', max_length=200),
        ),
        migrations.AddField(
            model_name='tipoeficacia',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='paginalistatratamento',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RemoveField(
            model_name='paginalistatratamento',
            name='template_name',
        ),
    ]
