# Generated by Django 5.1.5 on 2026-03-05 12:45
from django.db import migrations
from django.utils.text import slugify


def popular_slugs(apps, schema_editor):
    TipoEficacia = apps.get_model("core", "TipoEficacia")

    usados = set(
        TipoEficacia.objects.exclude(slug__isnull=True).exclude(slug="").values_list("slug", flat=True)
    )

    for obj in TipoEficacia.objects.all():
        # se já tem slug, pula
        if obj.slug:
            usados.add(obj.slug)
            continue

        base = slugify(getattr(obj, "tipo_eficacia", "") or getattr(obj, "nome", "") or str(obj.pk))
        if not base:
            base = f"tipo-{obj.pk}"

        slug_final = base
        i = 2
        while slug_final in usados:
            slug_final = f"{base}-{i}"
            i += 1

        obj.slug = slug_final
        obj.save(update_fields=["slug"])
        usados.add(slug_final)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0135_rename_condicao_paginalistatratamento_condicao_saude_and_more"),
    ]

    operations = [
        migrations.RunPython(popular_slugs, migrations.RunPython.noop),
    ]