# Generated by Django 5.1.5 on 2026-03-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_popular_slugs_tipoeficacia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoeficacia',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True),
        ),
    ]
