# Generated by Django 5.1.5 on 2026-03-12 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_alter_tipoeficacia_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentUSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('description_en', models.TextField(blank=True)),
                ('active_ingredient_en', models.CharField(blank=True, max_length=20000)),
                ('manufacturer_en', models.CharField(blank=True, max_length=200)),
                ('when_to_use_en', models.TextField(blank=True)),
                ('warnings_en', models.TextField(blank=True, null=True)),
                ('cost_specification_en', models.CharField(blank=True, max_length=200)),
                ('reason_children_en', models.TextField(blank=True, null=True)),
                ('reason_teens_en', models.TextField(blank=True, null=True)),
                ('reason_elderly_en', models.TextField(blank=True, null=True)),
                ('reason_adults_en', models.TextField(blank=True, null=True)),
                ('reason_lactating_en', models.TextField(blank=True, null=True)),
                ('reason_pregnancy_en', models.TextField(blank=True, null=True)),
                ('tratamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usa', to='core.detalhestratamentoresumo')),
            ],
            options={
                'verbose_name': 'Treatment USA',
                'verbose_name_plural': 'Treatments USA',
            },
        ),
    ]
