# Generated by Django 5.1.5 on 2026-03-12 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_treatmentusa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TreatmentUSA',
        ),
    ]
