# Generated by Django 5.1.5 on 2026-03-12 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_delete_treatmentusa'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentsUSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category')),
                ('clinical_evidence', models.TextField(blank=True, null=True, verbose_name='Clinical evidence')),
                ('active_ingredient', models.CharField(blank=True, max_length=20000, verbose_name='Active ingredient')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Manufacturer')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Rating')),
                ('efficacy_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Min efficacy')),
                ('efficacy_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Max efficacy')),
                ('effect_time_min', models.IntegerField(blank=True, null=True, verbose_name='Min effect time')),
                ('effect_time_max', models.IntegerField(blank=True, null=True, verbose_name='Max effect time')),
                ('effect_time_unit', models.CharField(choices=[('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('session', 'Session'), ('second', 'Second'), ('week', 'Weeks')], default='minute', max_length=10, verbose_name='Effect time unit')),
                ('treatment_purchase_link', models.URLField(blank=True, null=True, verbose_name='Treatment purchase link')),
                ('cost_specification', models.CharField(blank=True, max_length=200, verbose_name='Cost specification')),
                ('drug_interaction', models.URLField(blank=True, null=True, verbose_name='Drug interaction')),
                ('generic_similar', models.URLField(blank=True, null=True, verbose_name='Generic/similar')),
                ('electronic_prescription', models.URLField(blank=True, null=True, verbose_name='Electronic prescription')),
                ('specialist_opinion', models.URLField(blank=True, null=True, verbose_name='Specialist opinion')),
                ('professional_links', models.URLField(blank=True, null=True, verbose_name='Professional links')),
                ('alert', models.TextField(blank=True, null=True, verbose_name='Alert')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tratamentos_usa/', verbose_name='Image')),
                ('detail_image', models.ImageField(blank=True, null=True, upload_to='tratamentos_usa/detalhes/', verbose_name='Detail image')),
                ('when_to_use', models.TextField(blank=True, verbose_name='When to use')),
                ('treatment_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Treatment cost')),
                ('external_links', models.TextField(blank=True, null=True, verbose_name='External links')),
                ('alerts', models.TextField(blank=True, null=True, verbose_name='Alerts')),
                ('group', models.CharField(choices=[('children', 'Children under 12 years'), ('teenagers', 'Teenagers 12 to 17 years'), ('elderly', 'Elderly 65+'), ('adults', 'Adults'), ('lactating', 'Lactating'), ('pregnancy', 'Pregnancy')], default='adults', max_length=20, verbose_name='Group')),
                ('indicated_children', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=100, verbose_name='Indicated for children')),
                ('reason_children', models.TextField(blank=True, null=True, verbose_name='Reason children')),
                ('indicated_teenagers', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=100, verbose_name='Indicated for teenagers')),
                ('reason_teenagers', models.TextField(blank=True, null=True, verbose_name='Reason teenagers')),
                ('indicated_elderly', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=100, verbose_name='Indicated for elderly')),
                ('reason_elderly', models.TextField(blank=True, null=True, verbose_name='Reason elderly')),
                ('indicated_adults', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='YES', max_length=100, verbose_name='Indicated for adults')),
                ('reason_adults', models.TextField(blank=True, null=True, verbose_name='Reason adults')),
                ('indicated_lactating', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='YES', max_length=100, verbose_name='Indicated for lactating')),
                ('reason_lactating', models.TextField(blank=True, null=True, verbose_name='Reason lactating')),
                ('indicated_pregnancy', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='YES', max_length=100, verbose_name='Indicated for pregnancy')),
                ('reason_pregnancy', models.TextField(blank=True, null=True, verbose_name='Reason pregnancy')),
                ('risk', models.FloatField(default=0.0, help_text='Risk percentage of side effects (0 to 100%)', verbose_name='Risk')),
                ('adverse_reactions', models.ManyToManyField(blank=True, related_name='usa_treatments_with_reaction', to='core.reacaoadversa', verbose_name='Adverse reactions')),
                ('contraindications', models.ManyToManyField(blank=True, related_name='usa_treatments_with_contraindication', to='core.contraindicacao', verbose_name='Contraindications')),
                ('health_conditions', models.ManyToManyField(blank=True, related_name='usa_treatments', to='core.condicaosaude', verbose_name='Health conditions')),
                ('tipos_eficacia', models.ManyToManyField(blank=True, to='core.eficaciaporevidencia', verbose_name='Efficacy types')),
                ('tratamento_br', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamentos_usa', to='core.detalhestratamentoresumo', verbose_name='Brazil treatment')),
                ('treatment_type', models.ManyToManyField(blank=True, to='core.tipotratamento', verbose_name='Treatment type')),
            ],
            options={
                'verbose_name': 'Treatment USA',
                'verbose_name_plural': 'Treatments USA',
            },
        ),
        migrations.CreateModel(
            name='TreatmentsUSAReacaoAdversaTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grau_comunalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('reacao_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reacao_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reacao_adversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usa_test_treatments', to='core.reacaoadversa')),
                ('treatment_usa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes_adversas_teste_detalhes', to='core.treatmentsusa')),
            ],
            options={
                'verbose_name': 'USA Treatment Adverse Reaction Test Detail',
                'verbose_name_plural': 'USA Treatment Adverse Reaction Test Details',
            },
        ),
        migrations.AddField(
            model_name='treatmentsusa',
            name='reacoes_adversas_teste',
            field=models.ManyToManyField(blank=True, related_name='usa_treatments_with_test_reaction', through='core.TreatmentsUSAReacaoAdversaTeste', to='core.reacaoadversa', verbose_name='Adverse reactions test'),
        ),
    ]
