# Generated by Django 5.1.5 on 2026-03-16 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_alter_detalhestratamentoresumo_custo_medicamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalhestratamentoreacaoadversa',
            options={},
        ),
    ]
