# Generated by Django 5.1.5 on 2026-03-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_alter_detalhestratamentoreacaoadversa_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoeficacia',
            name='outcome_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
