# Generated by Django 5.1.5 on 2026-03-18 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_tipoeficacia_outcome_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eficaciaporevidencia',
            name='feito_pesquisa_com_placebo',
            field=models.BooleanField(default=False, verbose_name='Feito pesquisa com placebo?'),
        ),
        migrations.AddField(
            model_name='eficaciaporevidencia',
            name='participantes_placebo_com_beneficio',
            field=models.IntegerField(default=0, verbose_name='Participantes placebo com benefício'),
        ),
        migrations.AddField(
            model_name='eficaciaporevidencia',
            name='participantes_receberam_placebo',
            field=models.IntegerField(default=0, verbose_name='Participantes que receberam placebo'),
        ),
        migrations.AddField(
            model_name='eficaciaporevidencia',
            name='tipo_eficacia_placebo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eficacia_placebo_tipos', to='core.tipoeficacia', verbose_name='Tipo eficácia usuários placebo'),
        ),
    ]
