# Generated by Django 5.1.5 on 2026-03-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_eficaciaporevidencia_feito_pesquisa_com_placebo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eficaciaporevidencia',
            name='participantes_placebo_com_beneficio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Participantes placebo com benefício'),
        ),
        migrations.AlterField(
            model_name='eficaciaporevidencia',
            name='participantes_receberam_placebo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Participantes que receberam placebo'),
        ),
    ]
