# Generated by Django 5.1.5 on 2026-04-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_alter_eficaciaporevidencia_participantes_placebo_com_beneficio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamentocondicao',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterUniqueTogether(
            name='tratamentocondicao',
            unique_together={('tratamento', 'condicao')},
        ),
    ]
