# Generated by Django 5.1.5 on 2026-04-06 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_alter_tratamentocondicao_descricao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tratamentocondicao',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='tratamentocondicao',
            unique_together=set(),
        ),
    ]
