# Generated by Django 5.1.5 on 2026-04-07 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_alter_tratamentocondicao_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentListUrlEnglish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True)),
                ('template', models.CharField(default='core/en/treatment_list.html', max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('efficacy_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='english_list_pages', to='core.tipoeficacia')),
                ('health_condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='english_list_pages', to='core.condicaosaude')),
            ],
            options={
                'verbose_name': 'URL List in English',
                'verbose_name_plural': 'URLs Lists in English',
                'constraints': [models.UniqueConstraint(fields=('health_condition', 'efficacy_type'), name='unique_english_list_per_condition_and_efficacy')],
            },
        ),
        migrations.CreateModel(
            name='TreatmentUrlEnglish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('custom_title', models.CharField(blank=True, max_length=255)),
                ('custom_description', models.TextField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=120)),
                ('cta_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_treatment_pages', to='core.condicaosaude')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_pages', to='core.treatmentsusa')),
            ],
            options={
                'verbose_name': 'URL Treatment',
                'verbose_name_plural': 'URLs Treatments',
                'unique_together': {('condition', 'treatment')},
            },
        ),
    ]
