# Generated by Django 5.1.5 on 2026-04-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_treatmentlisturlenglish_treatmenturlenglish'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoeficacia',
            name='peso',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tipoeficacia',
            name='outcome_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
