# Generated by Django 5.1.5 on 2026-04-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_tipoeficacia_peso_alter_tipoeficacia_outcome_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoeficacia',
            name='peso',
        ),
    ]
