# Generated by Django 5.1.5 on 2026-04-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_remove_tipoeficacia_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoeficacia',
            name='outcome_slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True),
        ),
    ]
