# Generated by Django 5.1.5 on 2026-04-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_tipoeficacia_outcome_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicaosaude',
            name='condition_slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='condicaosaude',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='condicaosaude',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True),
        ),
    ]
