# Generated by Django 5.1.5 on 2026-04-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_condicaosaude_condition_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginalistatratamento',
            name='tratamentos_ocultos',
            field=models.ManyToManyField(blank=True, related_name='listas_em_que_foi_ocultado', to='core.detalhestratamentoresumo', verbose_name='Tratamentos ocultos desta lista'),
        ),
    ]
