# Generated by Django 5.1.5 on 2026-04-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_paginalistatratamento_tratamentos_ocultos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamentocondicao',
            name='aparecer_na_lista',
            field=models.BooleanField(default=True, verbose_name='Aparecer na lista da doença'),
        ),
        migrations.AlterField(
            model_name='tratamentocondicao',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='tratamentocondicao',
            unique_together={('tratamento', 'condicao')},
        ),
    ]
