# Generated by Django 5.1.5 on 2026-04-30 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_tratamentocondicao_aparecer_na_lista_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentsUSACondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('appear_on_list', models.BooleanField(default=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usa_treatment_relations', to='core.condicaosaude')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_relations', to='core.treatmentsusa')),
            ],
            options={
                'unique_together': {('treatment', 'condition')},
            },
        ),
    ]
