# Generated by Django 5.1.5 on 2026-05-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_treatmentsusacondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='imagem_anv',
            field=models.ImageField(blank=True, null=True, upload_to='tratamentos/'),
        ),
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='imagem_detalhes_anv',
            field=models.ImageField(blank=True, null=True, upload_to='tratamentos/detalhes/'),
        ),
    ]
