# Generated by Django 5.1.5 on 2026-06-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_detalhestratamentoresumo_imagem_anv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='especificacao_tecnica_para_medicos',
            field=models.FileField(blank=True, null=True, upload_to='pdf_especificacao_medicos/'),
        ),
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='especificacao_tecnica_para_pacientes',
            field=models.FileField(blank=True, null=True, upload_to='pdf_especificacao_pacientes/'),
        ),
    ]
