# Generated by Django 5.1.5 on 2026-06-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_detalhestratamentoresumo_especificacao_tecnica_para_medicos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='circunstancias_risco_morte',
            field=models.TextField(blank=True, null=True, verbose_name='Circunstâncias de risco de morte'),
        ),
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='circunstancias_risco_permanente_saude',
            field=models.TextField(blank=True, null=True, verbose_name='Circunstâncias de risco permanente à saúde'),
        ),
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='risco_dano_irreversivel_saude',
            field=models.BooleanField(default=False, verbose_name='Risco de dano irreversível à saúde?'),
        ),
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='risco_morte',
            field=models.BooleanField(default=False, verbose_name='Risco de morte?'),
        ),
    ]
