# Generated by Django 5.1.5 on 2026-06-25 17:34

import django.contrib.admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('core', '0158_detalhestratamentoresumo_circunstancias_risco_morte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeUsuario',
            fields=[
            ],
            options={
                'verbose_name': 'Atividade do usuário',
                'verbose_name_plural': 'Atividades dos usuários',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin.logentry',),
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='categoria_regulatoria',
            field=models.CharField(blank=True, choices=[('novo', 'Novo'), ('referencia', 'Referência'), ('similar', 'Similar'), ('generico', 'Genérico'), ('fitoterapico', 'Fitoterápico'), ('biologico', 'Biológico'), ('especifico', 'Específico'), ('dinamizado', 'Dinamizado'), ('radiofarmaco', 'Radiofármaco'), ('gases_medicinais', 'Gases medicinais'), ('nao_aplicavel', 'Não aplicável')], max_length=50, null=True, verbose_name='Categoria regulatória'),
        ),
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='tipo_prescricao',
            field=models.CharField(blank=True, choices=[('isento_de_prescricao', 'Isento de prescrição'), ('tarja_vermelha', 'Tarja vermelha'), ('tarja_preta', 'Tarja preta'), ('nao_medicamentosos', 'Não medicamentosos')], max_length=50, null=True, verbose_name='Tipo de prescrição'),
        ),
    ]
