# Generated by Django 5.1.5 on 2026-06-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_atividadeusuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='id_tratamento',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Informe o código EAN ou códigos de referência do medicamento. Para múltiplos códigos, separe por vírgula.', max_length=255, verbose_name='ID tratamento / Código EAN'),
        ),
    ]
