# Generated by Django 5.1.5 on 2026-07-20 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0160_detalhestratamentoresumo_id_tratamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegurancaUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(choices=[('criancas', 'Crianças'), ('adolescentes', 'Adolescentes'), ('idosos', 'Idosos'), ('adultos', 'Adultos'), ('lactantes', 'Lactantes'), ('gravidez', 'Gravidez')], max_length=30, verbose_name='Grupo')),
                ('tem_seguranca_uso', models.BooleanField(default=False, verbose_name='Tem segurança de uso?')),
                ('motivo', models.TextField(blank=True, default='', verbose_name='Motivo')),
                ('numero_participantes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de participantes')),
                ('autores', models.TextField(blank=True, default='', verbose_name='Autores')),
                ('link_estudo', models.URLField(blank=True, default='', max_length=1000, verbose_name='Link do estudo')),
                ('data_publicacao', models.DateField(blank=True, null=True, verbose_name='Data de publicação')),
                ('paises', models.CharField(blank=True, default='', max_length=500, verbose_name='Países')),
                ('titulo', models.CharField(blank=True, default='', max_length=500, verbose_name='Título')),
                ('fonte_local_publicacao', models.CharField(blank=True, default='', max_length=500, verbose_name='Fonte / local de publicação')),
                ('imagem_local_publicacao', models.ImageField(blank=True, null=True, upload_to='seguranca_uso/fontes/', verbose_name='Imagem do local de publicação')),
                ('descricao_pesquisa', models.TextField(blank=True, default='', verbose_name='Descrição da pesquisa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tratamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='segurancas_uso', to='core.detalhestratamentoresumo', verbose_name='Tratamento')),
            ],
            options={
                'verbose_name': 'Segurança de uso',
                'verbose_name_plural': 'Segurança de uso',
                'ordering': ['tratamento__nome', 'grupo', '-data_publicacao'],
            },
        ),
    ]
