# Generated by Django 5.1.5 on 2026-07-20 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0161_segurancauso'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFatorRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome do tipo de fator de risco')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tipo de fator de risco',
                'verbose_name_plural': 'Tipos de fatores de risco',
                'db_table': 'tipos_fatores_risco',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FatorRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do fator de risco')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição do fator de risco')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('condicao_saude', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fatores_risco', to='core.condicaosaude', verbose_name='Condição de saúde')),
                ('tipo_fator_risco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fatores_risco', to='core.tipofatorrisco', verbose_name='Tipo do fator de risco')),
            ],
            options={
                'verbose_name': 'Fator de risco',
                'verbose_name_plural': 'Fatores de risco',
                'db_table': 'fatores_risco',
                'ordering': ['condicao_saude__nome', 'tipo_fator_risco__nome', 'nome'],
            },
        ),
    ]
