# Generated by Django 5.1.5 on 2026-07-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_tipofatorrisco_fatorrisco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatorrisco',
            name='tipo_fator_risco',
            field=models.CharField(choices=[('genetico', 'Genético'), ('comportamental', 'Comportamental'), ('ambiental', 'Ambiental'), ('clinico', 'Clínico'), ('hormonal', 'Hormonal'), ('alimentar', 'Alimentar'), ('historico_familiar', 'Histórico familiar'), ('outro', 'Outro')], max_length=50, verbose_name='Tipo do fator de risco'),
        ),
        migrations.AlterModelOptions(
            name='fatorrisco',
            options={'ordering': ['condicao_saude__nome', 'tipo_fator_risco', 'nome'], 'verbose_name': 'Fator de risco', 'verbose_name_plural': 'Fatores de risco'},
        ),
        migrations.AlterModelTable(
            name='fatorrisco',
            table=None,
        ),
        migrations.DeleteModel(
            name='TipoFatorRisco',
        ),
    ]
