# Generated by Django 5.1.5 on 2026-07-20 18:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0163_alter_fatorrisco_tipo_fator_risco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaFatorRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlacao_ou_causa', models.CharField(choices=[('correlacao', 'Correlação'), ('causa', 'Causa')], max_length=20, verbose_name='Correlação ou causa')),
                ('grupo', models.CharField(choices=[('criancas', 'Crianças'), ('adolescentes', 'Adolescentes'), ('idosos', 'Idosos'), ('adultos', 'Adultos'), ('lactantes', 'Lactantes'), ('gravidez', 'Gravidez')], max_length=30, verbose_name='Grupo')),
                ('prevalencia', models.DecimalField(blank=True, decimal_places=2, help_text='Informe o percentual entre 0 e 100.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Prevalência (%)')),
                ('requer_exposicao', models.BooleanField(default=False, verbose_name='Requer exposição a algum agente/situação para ser fator de risco?')),
                ('agentes_situacoes_necessarias', models.TextField(blank=True, default='', verbose_name='Agentes/situações necessárias para esse item ser um fator de risco')),
                ('ano_dados_coletados', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Data dos dados coletados (ano)')),
                ('pais_dados_pesquisados', models.CharField(blank=True, default='', max_length=255, verbose_name='País dos dados pesquisados')),
                ('rigor_pesquisa', models.CharField(blank=True, default='', help_text='Ex.: alto, médio, baixo, revisão sistemática, estudo observacional, metanálise etc.', max_length=255, verbose_name='Rigor da pesquisa')),
                ('quantidade_participantes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de participantes')),
                ('data_pesquisa', models.DateField(blank=True, null=True, verbose_name='Data da pesquisa')),
                ('pais_pesquisa', models.CharField(blank=True, default='', max_length=255, verbose_name='País da pesquisa')),
                ('nomes_autores', models.TextField(blank=True, default='', verbose_name='Nomes dos autores')),
                ('titulo_pesquisa', models.CharField(max_length=500, verbose_name='Título da pesquisa')),
                ('tipo_identificador_pesquisa', models.CharField(blank=True, default='', help_text='Ex.: DOI, PMID, ClinicalTrials.gov, outro.', max_length=100, verbose_name='Tipo de identificador da pesquisa')),
                ('identificador_pesquisa', models.CharField(blank=True, default='', max_length=255, verbose_name='Identificador DOI ou outro identificador da pesquisa')),
                ('descricao_pesquisa', models.TextField(blank=True, default='', verbose_name='Descrição da pesquisa')),
                ('link_pesquisa', models.URLField(blank=True, default='', max_length=1000, verbose_name='Link para a pesquisa')),
                ('arquivo_pdf_pesquisa', models.FileField(blank=True, null=True, upload_to='evidencias_fatores_risco/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Subir pesquisa em PDF')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('condicao_saude', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_fatores_risco', to='core.condicaosaude', verbose_name='Condição de saúde')),
                ('fator_risco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_fatores_risco', to='core.fatorrisco', verbose_name='Fator de risco')),
            ],
            options={
                'verbose_name': 'Evidência fator de risco',
                'verbose_name_plural': 'Evidências fatores de risco',
                'db_table': 'evidencias_fatores_risco',
                'ordering': ['condicao_saude__nome', 'fator_risco__nome', 'grupo', '-data_pesquisa'],
            },
        ),
    ]
