# Generated by Django 5.1.5 on 2026-07-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0164_evidenciafatorrisco'),
    ]

    operations = [
        migrations.AddField(
            model_name='segurancauso',
            name='rigor_da_pesquisa',
            field=models.IntegerField(default=0, verbose_name='Rigor da pesquisa'),
        ),
        migrations.RemoveField(
            model_name='segurancauso',
            name='paises',
        ),
        migrations.AddField(
            model_name='segurancauso',
            name='paises',
            field=models.ManyToManyField(blank=True, to='core.pais', verbose_name='Países'),
        ),
    ]
