# Generated by Django 5.1.5 on 2026-07-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_segurancauso_rigor_da_pesquisa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidenciafatorrisco',
            name='pais_dados_pesquisados',
        ),
        migrations.AlterField(
            model_name='evidenciafatorrisco',
            name='rigor_pesquisa',
            field=models.IntegerField(default=0, verbose_name='Rigor da pesquisa'),
        ),
        migrations.AddField(
            model_name='evidenciafatorrisco',
            name='pais_dados_pesquisados',
            field=models.ManyToManyField(blank=True, to='core.pais', verbose_name='País da Pesquisa'),
        ),
    ]
