# Generated by Django 5.1.5 on 2026-07-27 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0166_remove_evidenciafatorrisco_pais_dados_pesquisados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciafatorrisco',
            name='pais_dados_pesquisados',
            field=models.ManyToManyField(blank=True, related_name='evidencias_fatores_risco_dados_pesquisados', to='core.pais', verbose_name='País dos dados pesquisados'),
        ),
        migrations.RemoveField(
            model_name='evidenciafatorrisco',
            name='pais_pesquisa',
        ),
        migrations.CreateModel(
            name='AlertaTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='', max_length=255, verbose_name='Título do alerta')),
                ('descricao', models.TextField(verbose_name='Descrição do alerta')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Use para controlar a ordem de exibição dos alertas.', verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tratamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_tratamento', to='core.detalhestratamentoresumo', verbose_name='Tratamento')),
            ],
            options={
                'verbose_name': 'Alerta do tratamento',
                'verbose_name_plural': 'Alertas do tratamento',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddField(
            model_name='evidenciafatorrisco',
            name='pais_pesquisa',
            field=models.ManyToManyField(blank=True, related_name='evidencias_fatores_risco_pesquisas', to='core.pais', verbose_name='País da pesquisa'),
        ),
    ]
