# Generated by Django 5.1.5 on 2026-07-30 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0167_alter_evidenciafatorrisco_pais_dados_pesquisados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginalistatratamento',
            name='tipos_eficacia',
            field=models.ManyToManyField(blank=True, help_text='Selecione todos os tipos de eficácia que deverão aparecer como filtros na mesma página.', related_name='paginas_listas_segmentadas', to='core.tipoeficacia', verbose_name='Tipos de eficácia'),
        ),
        migrations.AlterField(
            model_name='paginalistatratamento',
            name='template',
            field=models.CharField(default='core/lista_tratamentos.html', help_text='Template Django que renderiza a lista', max_length=200),
        ),
        migrations.AlterField(
            model_name='paginalistatratamento',
            name='tipo_eficacia',
            field=models.ForeignKey(blank=True, help_text='Campo antigo mantido temporariamente para compatibilidade.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paginas_listas_legacy', to='core.tipoeficacia', verbose_name='Tipo de eficácia antigo'),
        ),
    ]
