# Generated by Django 5.1.5 on 2026-07-30 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0168_paginalistatratamento_tipos_eficacia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaListaTratamentoV2',
            fields=[
            ],
            options={
                'verbose_name': 'URLs Listas V2',
                'verbose_name_plural': 'URLs Listas V2',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.paginalistatratamento',),
        ),
    ]
