# Generated by Django 5.1.5 on 2026-08-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0169_paginalistatratamentov2'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhestratamentoresumo',
            name='codigo_anvisa',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Informe o número de registro do produto na ANVISA. Para múltiplos códigos, separe por vírgula.', max_length=255, verbose_name='Código ANVISA'),
        ),
    ]
