# Generated by Django 5.1.5 on 2026-09-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0170_detalhestratamentoresumo_codigo_anvisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhestratamentoresumo',
            name='link_para_compra_de_tratamento',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
