# Generated by Django 5.1.5 on 2026-09-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0171_alter_detalhestratamentoresumo_link_para_compra_de_tratamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhestratamentoresumo',
            name='link_para_compra_de_tratamento',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidenciasclinicas',
            name='autores',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
