# Generated by Django 5.1.5 on 2026-09-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0172_alter_detalhestratamentoresumo_link_para_compra_de_tratamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhestratamentoresumo',
            name='link_para_compra_de_tratamento',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
